### ISSUE TITLE
expHTS preprocess -s option issue

### ISSUE THREAD

**Issue by benn0078** [msettles/expHTS#17]
I ran:
expHTS preprocess -s -a -O -F 02-Cleaned_dups -w -t 12
with the -s option to see how leaving duplicates affected my results.

I didn't receive any warnings or errors, but my read counts are off for the cleaned fastq files:

Raw read count:
sed -n '1~4p' B2ST1_TTAGGC_L005_R1_001.fastq | grep "^@" | wc -l
6948683

Cleaned read count after running the above command:
sed -n '1~4p' B2_R1.fastq | grep "^@" | wc -l
12843598
(twice as much as it should be based on my calculations from the preprocessing summary)

First 10 lines of the cleaned fastq file:
head -10 B2_R1.fastq
@HWI-D00289:175:C6K3VANXX:5:1101:1661:2064#0/1
GATGCTTACAAATACAGAGAGACATTTAGATGTGCACCGTCGTCGTCGTCGTCACGCTCGTTCACACACGCGCGCACAAAAGGAAGAAAAAAAGACTTAAGACAAAAGGTTTAAGTACTACAGAC
+
<<BBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF<FFFFFFFFBFFFFFFFFFFFFFFFFFFFFF<FFFFFFFFFFFFFFFB
@HWI-D00289:175:C6K3VANXX:5:1101:4385:2074#0/1
GCTAGCTTCTGTATTAAGTCGTAGAGCAGATATATCCCAAACTAATGAAACGTCCTCTCCCCATTTATGAACAAAGTCATTTAACAACATATAGTACCAGGTGTGCGCTATCAGAGTATCCACGAA
+
BBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@HWI-D00289:175:C6K3VANXX:5:1101:4383:2135#0/1
GTCGAACAAACACATTTGATGACTTTAAACTGTTGAATTAGGGTTTTAACTTATGAAGCGATGGATAAATGAGCAGTCCAGGCTAGTTGTAGGGTTTACTGGCTTCCACTGAAATAGGACACAAAG

Cleaned read count WITHOUT the -s option:
5368273

Files are located: /mnt/home/mbenner/GRC_Pipeline/02-Cleaned_dups

Thank you!

**Comment by dstreett** [comment]
Good catch @benn0078 . I duplicated the screening call. @msettles - this is why processing time doubled over night. Duplicates were caught with the deduper but once that was turned off duplicates reads got through.
