### ISSUE TITLE
Flag to skip deduping

### ISSUE THREAD

**Issue by bricesarver** [msettles/expHTS#30]
There are some applications where you wouldn't want to dedup but still do the other stuff. A flag would be a welcome addition for some things other people are working on (expression and all that - not necessarily anything I'm doing currently).

**Comment by dstreett** [comment]
It should be -s , is that not in the master branch?

**Comment by bricesarver** [comment]
uhhhhhhhhhh my bad

**Comment by dstreett** [comment]
No worries! Let me know if you run into any more issues!
