### ISSUE TITLE
not portable to OSX

### ISSUE THREAD

**Issue by bricesarver** [msettles/expHTS#32]
Not sure if you want this installable outside of Linux distos at first, but there are errors and warnings thrown when trying to install at least on OS X 10.10.5. Appears restricted to finalCleanup.

**Comment by msettles** [comment]
More specifically

gcc -fno-strict-aliasing -I/Users/mattsettles/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/mattsettles/anaconda/include/python2.7 -c lib/finalCleanup.c -o build/temp.macosx-10.5-x86_64-2.7/lib/finalCleanup.o
lib/finalCleanup.c:342:13: warning: unused variable 'i' [-Wunused-variable]
        int i = 0;
            ^
lib/finalCleanup.c:543:3: warning: format specifies type 'int' but the argument has type 'unsigned long long' [-Wformat]
                R1_len/(s.pe_kept), R2_len/(s.pe_kept), SE_len/(s.se_kept), (float)((float)(s.qualTotal)/(float)(s.A + s.T + s.C + s.G + s.N)));
                ^~~~~~~~~~~~~~~~~~
lib/finalCleanup.c:543:23: warning: format specifies type 'int' but the argument has type 'unsigned long long' [-Wformat]
                R1_len/(s.pe_kept), R2_len/(s.pe_kept), SE_len/(s.se_kept), (float)((float)(s.qualTotal)/(float)(s.A + s.T + s.C + s.G + s.N)));
                                    ^~~~~~~~~~~~~~~~~~
lib/finalCleanup.c:543:43: warning: format specifies type 'int' but the argument has type 'unsigned long long' [-Wformat]
                R1_len/(s.pe_kept), R2_len/(s.pe_kept), SE_len/(s.se_kept), (float)((float)(s.qualTotal)/(float)(s.A + s.T + s.C + s.G + s.N)));
                                                        ^~~~~~~~~~~~~~~~~~
lib/finalCleanup.c:540:110: warning: more '%' conversions than data arguments [-Wformat]
        fprintf(log, "%llu\t%llu\t%llu\t%llu\t%llu\t%llu\t%llu\t%llu\t%llu\t%llu\t%llu\t%d\t%d\t%d\t%.2f\t%.2f\t%.2f\n", s.A, s.T, s.G, s.C, s.N, s.polyATrimmed, s.polyTTrimmed, s.r1_discarded + s.r2_discarded + s.se_discarded, s.pe_kept, s.se_kept, s.numForcedPairs,
                                                                                                          ~~~^
lib/finalCleanup.c:563:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
lib/finalCleanup.c:576:8: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        clean(devFile, logFile, R1, R2, SE, split, polyAT);
              ^~~~~~~
lib/finalCleanup.c:420:17: note: passing argument to parameter 'devFile' here
int clean(char *devFile, char *logFile, char *strR1, char *strR2, char *strSE, int tmpforcePairs, int tmpPolyATTrim) {
                ^
lib/finalCleanup.c:576:17: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        clean(devFile, logFile, R1, R2, SE, split, polyAT);
                       ^~~~~~~
lib/finalCleanup.c:420:32: note: passing argument to parameter 'logFile' here
int clean(char *devFile, char *logFile, char *strR1, char *strR2, char *strSE, int tmpforcePairs, int tmpPolyATTrim) {
                               ^
lib/finalCleanup.c:576:26: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        clean(devFile, logFile, R1, R2, SE, split, polyAT);
                                ^~
lib/finalCleanup.c:420:47: note: passing argument to parameter 'strR1' here
int clean(char *devFile, char *logFile, char *strR1, char *strR2, char *strSE, int tmpforcePairs, int tmpPolyATTrim) {
                                              ^
lib/finalCleanup.c:576:30: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        clean(devFile, logFile, R1, R2, SE, split, polyAT);
                                    ^~
lib/finalCleanup.c:420:60: note: passing argument to parameter 'strR2' here
int clean(char *devFile, char *logFile, char *strR1, char *strR2, char *strSE, int tmpforcePairs, int tmpPolyATTrim) {
                                                           ^
lib/finalCleanup.c:576:34: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        clean(devFile, logFile, R1, R2, SE, split, polyAT);
                                        ^~
lib/finalCleanup.c:420:73: note: passing argument to parameter 'strSE' here
int clean(char *devFile, char *logFile, char *strR1, char *strR2, char *strSE, int tmpforcePairs, int tmpPolyATTrim) {
                                                                        ^
lib/finalCleanup.c:603:2: error: void function 'initfinalCleanup' should not return a value [-Wreturn-type]
        return NULL;

At least on my machine

Matt

From:  Brice Sarver notifications@github.com
Reply-To:  msettles/expHTS reply@reply.github.com
Date:  Wednesday, October 21, 2015 at 9:55 PM
To:  msettles/expHTS expHTS@noreply.github.com
Subject:  [expHTS] not portable to OSX (#32)

Not sure if you want this installable outside of Linux distos at first, but there are errors and warnings thrown when trying to install at least on OS X 10.10.5. Appears restricted to finalCleanup.

—
Reply to this email directly or view it on GitHub.

**Comment by dstreett** [comment]
I will definitely update this. The OSX issue is that they are actually using clang and not gcc. I can get away with some things on Linux that I can't on a Mac.

**Comment by dstreett** [comment]
Should be good to go now (works on El Capitan)! Still some error (const *char to char, int long to int) but nothing that changes the results. Let me know if there are any issues.
